// ─── src/models/Conversation.js ──────────────────────────────────────────────
//
// This defines the shape (schema) of the data stored in MongoDB for each
// conversation session.
//
// Each document represents one user's full conversation history, keyed by
// their sessionId (a UUID generated by the React frontend).
//
// SCHEMA STRUCTURE:
//
//   sessionId  (string, unique) — the UUID from the browser that identifies
//                                  this conversation across page reloads
//
//   messages   (array of objects) — each object has:
//     role       ("user" | "assistant") — who said it
//     content    (string)               — what was said
//     createdAt  (Date)                 — when it was said
//
//   updatedAt  (Date) — automatically updated by Mongoose whenever the
//                       document is saved (used to see recent activity)
//
// WHY MONGODB?
// A document database is a natural fit here because each conversation is a
// self-contained unit. There are no JOINs needed — the full history lives in
// one document and can be fetched with a single query.
// ─────────────────────────────────────────────────────────────────────────────

const mongoose = require('mongoose');

// ── Sub-schema: a single message turn ────────────────────────────────────────
const MessageSchema = new mongoose.Schema(
  {
    // Claude API expects "user" or "assistant" exactly
    role: {
      type:     String,
      enum:     ['user', 'assistant'],
      required: true,
    },
    // The text content of the message
    content: {
      type:     String,
      required: true,
    },
  },
  {
    // Automatically add a createdAt timestamp to each message sub-document
    timestamps: { createdAt: 'createdAt', updatedAt: false },
  }
);

// ── Main conversation schema ──────────────────────────────────────────────────
const ConversationSchema = new mongoose.Schema(
  {
    // Unique per browser session
    sessionId: {
      type:     String,
      required: true,
      unique:   true,
      index:    true,   // fast lookups by sessionId on every request
    },

    // Array of all message turns in this conversation
    messages: [MessageSchema],
  },
  {
    // Mongoose automatically manages createdAt and updatedAt on the document
    timestamps: true,
  }
);

// Export the model so it can be imported in the chat controller
module.exports = mongoose.model('Conversation', ConversationSchema);
